FROM ubuntu:artful

RUN apt-get update -y && \
    apt-get install -y software-properties-common python-software-properties lsb-core lsb-release expect iproute2

WORKDIR /opt/test

CMD tail -f /dev/null
