os:
  - linux
  - osx

dist: trusty
sudo: required

services:
- docker

script:
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then bash test/run.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash test/run-macos.sh; fi

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: setupsh-badges
  github-token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master