dist: trusty
sudo: required

services:
- docker

script:
- bash test/run.sh

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: setupsh-badges
  github-token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master