dist: trusty
sudo: required

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_721e549d5880_key -iv $encrypted_721e549d5880_iv
  -in id_rsa.travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- sudo sysctl -w vm.max_map_count=262144

script:
- bash test/run.sh

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: setupsh-badges
  github-token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master
