version: '2'

services:
  proxy:
    image: kuzzleio/proxy
    ports:
      - "7512:7512"

  backoffice:
    image: kuzzleio/backoffice
    environment:
      - BACKOFFICE_PORT=3000
    ports:
      - 3000:3000

  kuzzle:
    image: kuzzleio/kuzzle
    cap_add:
      - SYS_PTRACE
    depends_on:
      - proxy
      - redis
      - elasticsearch
    environment:
      - kuzzle_services__db__host=elasticsearch
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_services__proxyBroker__host=proxy

  redis:
    image: redis:3.2-alpine

  elasticsearch:
    image: elasticsearch:5.0
